//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatBookerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        public int ID { get; set; }
        public string Chart_ID { get; set; }
        public Nullable<int> Seat_Row { get; set; }
        public Nullable<int> Seat_Column { get; set; }
        public string Row_Div_No { get; set; }
        public string Col_Div_No { get; set; }
        public Nullable<int> Log_Id { get; set; }
    }
}
