//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatBookerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seating
    {
        public int ID { get; set; }
        public string Hold_Places { get; set; }
        public string User_Name { get; set; }
        public string Event_Name { get; set; }
    }
}
